// @goldpan/web-sdk — framework-agnostic client + types + errors

export { GoldpanClient } from './client';
export { GoldpanApiError } from './errors';
export type {
  // Knowledge
  Category,
  CategoryTree,
  CitedEntity,
  // Settings (env-file editing)
  CommitEnvResult,
  // Conversations
  ConversationDetail,
  ConversationListParams,
  ConversationMessage,
  ConversationSummary,
  // Interest / Tracking
  CreateInterestInput,
  CreateNoteInput,
  // Debug
  DebugTask,
  DebugTaskDetail,
  DigestChannelSlot,
  DigestConnection,
  DigestConnectionsParams,
  DigestDataSnapshot,
  DigestPeriod,
  DigestPreset,
  DigestRelationType,
  DigestRenderPreset,
  DigestShareResponse,
  DigestSnapshotModules,
  DigestSnapshotResponse,
  DigestSnapshotStatus,
  DualProcessRestartKey,
  Entity,
  EntityDetail,
  EntityListParams,
  EntityNameLookupResult,
  EntityRelation,
  EntitySource,
  EnvKeyState,
  EnvStateResponse,
  EventLog,
  // GitHub
  GithubRefreshResult,
  GithubRepoState,
  GithubRepoSummary,
  // Client options
  GoldpanClientOptions,
  // Health
  HealthChannelView,
  HealthStatus,
  // IM settings manifest + actions
  ImActionResult,
  ImSettingsActionDescriptor,
  ImSettingsField,
  ImSettingsManifest,
  ImSetupGuideStep,
  InputActionResult,
  InputClarifyResult,
  InputContentResult,
  InputQueryResult,
  // Input
  InputResult,
  InputSubmitAccepted,
  InputSubmitDuplicate,
  InputSubmitRejected,
  InputSubmitResult,
  Interest,
  InterestDetail,
  InterestExecution,
  InterestExecutionDetail,
  InterestExecutionListParams,
  InterestExecutionListResult,
  InterestItem,
  InterestLinkedEntity,
  InterestListItem,
  KnowledgePoint,
  ListNotesParams,
  ListNotesResult,
  LlmCallDetail,
  LlmCallMeta,
  LlmProviderBuiltin,
  LlmProviderCustom,
  LlmProviderPlugin,
  LlmProvidersResponse,
  LocalizedString,
  LoginResult,
  ManagedEnvKey,
  MarkNoteRemindedOptions,
  MarkNoteRemindedResult,
  NoteDetail,
  NoteSourceRelation,
  NoteSubtype,
  // Generic
  PaginatedList,
  // Plugin Settings Contribution (new generic protocol)
  PluginActionDescriptor,
  PluginActionResult,
  // Plugins (settings page)
  PluginConfigGroupId,
  PluginInfo,
  PluginNoticeDescriptor,
  PluginSettingsContributionDescriptor,
  PluginSettingsContributionsResponse,
  PluginSettingsGroup,
  PluginSetupGuideDescriptor,
  PluginSetupStepDescriptor,
  PluginsSnapshot,
  PluginType,
  PromoteNoteResult,
  // Query
  QueryResult,
  // Tracking probe
  SearchToolStatus,
  ServerRestartResult,
  SettingsFieldDescriptor,
  SettingsFieldKind,
  // Sources
  SourceDetail,
  SourceListItem,
  SourceListParams,
  SourceListResponse,
  SourceStatus,
  SourceStatusCounts,
  // SourceView (source-view library types — formerly Note*)
  SourceViewDetail,
  SourceViewEntityGroup,
  SourceViewListItem,
  SourceViewListParams,
  SourceViewListResult,
  SourceViewMeta,
  SourceViewStats,
  SubmissionLog,
  SubmitAccepted,
  SubmitDuplicate,
  SubmitRejected,
  // Submit
  SubmitResult,
  // Auth
  SystemStatus,
  Task,
  TaskDetail,
  TaskDone,
  TaskError,
  // Tasks
  TaskErrorKind,
  TaskListParams,
  TaskListResponse,
  TaskLog,
  TaskPending,
  TaskProcessing,
  TaskSource,
  TaskStatus,
  TaskStatusCounts,
  TranslateNoteResult,
  UpdateInterestInput,
  UpdateNoteInput,
} from './types';
export {
  DUAL_PROCESS_RESTART_KEYS,
  MANAGED_ENV_KEYS,
  NOTE_SUBTYPES,
  PROMOTE_NOTE_MIN_CONTENT_LENGTH,
  TASK_ERROR_KINDS,
} from './types';
